[workspace]
resolver = "3"
members = [
    "sunangle",
    "coordinate-systems",
    "ecs-namespace",
    "video",
    "world-model",
]
default-members = [
    "sunangle",
    "coordinate-systems",
    "ecs-namespace",
    "video",
    "world-model",
]

[workspace.package]
edition = "2024"
rust-version = "1.85"

[workspace.dependencies] #===================== dependencies (all targets) =========================

#------------------------------------------ Defined in this workspace

coordinate-systems = { path = "./coordinate-systems" }
video = { path = "./video" }
ecs-namespace = { path = "./ecs-namespace" }
world-model = { path = "./world-model" }

#------------------------------------------ `three-d` and `three-d-asset`

# https://github.com/asny/three-d/blob/0.19.0/Cargo.toml
three-d = {
    version = "0.19.0",
    # git = "https://github.com/asny/three-d",
    # rev = "b6b0963bc0cee707671e877c42040cb8c4147991",
    default-features = false
}

# https://github.com/asny/three-d-asset/blob/0.10.0/Cargo.toml
three-d-asset = {
    version = "0.10",
    # git = "https://github.com/asny/three-d-asset",
    # rev = "8f18012480a9ed6f78e9d26d0ee260310a9ddeb7",
    # [three-d 0.19.0 unconditionally depends on three-d-asset 0.10 with default features] default-features = false
    features = [
        "reqwest",
        "jpeg",
    ]
}

#---- Keep these in sync with whatever the `three-d` crate is using
glow = "0.17"
cgmath = "0.18"
thiserror = "2"
# open-enum = "0.5"
# winit
egui = "0.34"
egui_glow = "0.34"
# swash = "0.2"
# lyon = "1"

#---- Keep these in sync with whatever the `three-d-asset` crate is using
# half = { version = "2", features = [ "std", "num-traits", "zerocopy" ] }
# thiserror
# reqwest
# gltf
# wavefront_obj
# stl_io
# lib3buibmf
# image
# resvg
# pcd-rs
# data-url
serde = {version= "1", features = ["derive", "rc"] }

#------------------------------------------ Common dependencies

anyhow = "1.0.102"
derive_more = { version = "2.1.1", default-features = false, features = [
        "deref", "deref_mut", "display", "from", "into"
    ] }
hecs = { version = "0.11.0", features = ["macros", "column-serialize", "row-serialize"] }
hecs-hierarchy = "0.13.0"
hecs-schedule = "0.8.0"
insta = { version = "1.47.2", features = ["glob", "redactions", "ron"] }
log = "0.4.29"
num_enum = { version = "0.7.6", default-features = false, features = [] } # Unwanted dependency "android-activity" uses 0.6.1
num-integer = { version = "0.1.46", features = [] }
num-rational = { version = "0.4.2", default-features = false, features = ["num-bigint", "serde", "std"] }
num-traits = { version = "0.2.19", features = [] }
once_cell = "1.21.4"
# ratelimit = "2.0"
ron = "0.12.1"
strum = { version = "0.28.0", features = ["derive"] }

#------------------------------------------ Futures, async

async-global-executor = { version = "3.1.0", default-features = false, }
    #features = [
    #    "async-io",
    #    "tokio",
    #]

#------- egui/eframe dependencies

# https://github.com/emilk/egui/blob/main/crates/eframe/Cargo.toml
eframe = {
    version = "0.34.2",
    default-features = false,
    features = [
        "accesskit",     # Make egui comptaible with screen readers
        "default_fonts", # Embed the default egui fonts
        "glow",          # Use the 'glow' rendering backend rather than 'wgpu'
        "persistence",   # Persist app state (window positions, etc)
    ]
}

#------- puffin dependencies

# https://github.com/EmbarkStudios/puffin/blob/7e08a533f9debfb7d051547263d2ab84c666314f/Cargo.toml
# https://github.com/EmbarkStudios/puffin/blob/7e08a533f9debfb7d051547263d2ab84c666314f/puffin/Cargo.toml
# https://github.com/EmbarkStudios/puffin/blob/7e08a533f9debfb7d051547263d2ab84c666314f/puffin_egui/Cargo.toml
puffin = "0.20.0"
puffin_egui = "0.30.0"

#puffin_http = "0.16.1"

profiling = { version = "1.0.17", default-features = false }

#========================================== patches ================================================

#------------------------------------------- puffin

[patch.crates-io.puffin]
version = "=0.20.0"
git = "https://github.com/EmbarkStudios/puffin"
rev = "7e08a533f9debfb7d051547263d2ab84c666314f"

[patch.crates-io.puffin_egui]
version = "=0.30.0"
git = "https://github.com/EmbarkStudios/puffin"
rev = "7e08a533f9debfb7d051547263d2ab84c666314f"

#------------------------------------------- hecs-hierarchy, hecs-schedule

[patch.crates-io.hecs-schedule]
version = "=0.8.0"
git = "https://github.com/marshray/hecs-schedule.git"
rev = "6a69a7a65fe46cdc0f3545d6e7680376b2ac32f0"
#path = "../marshray/forked-hecs-heirarchy-schedule/hecs-hierarchy"

[patch.crates-io.hecs-hierarchy]
version = "=0.13.0"
git = "https://github.com/marshray/hecs-hierarchy.git"
rev = "27cff704e91a2e8c514f3a04be3a482df0e94efa"
#path = "../marshray/forked-hecs-heirarchy-schedule/hecs-hierarchy"

#=================================  profile settings ===============================================

[profile.release]
opt-level = 2 # fast and small wasm

# Optimize all dependencies even in debug builds:
[profile.dev.package."*"]
opt-level = 2

