[package]
name = "ecs-namespace"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
derive_more.workspace = true
hecs.workspace = true
hecs-hierarchy.workspace = true

[dev-dependencies]
insta.workspace = true
