[package]
name = "coordinate-systems"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true

[dependencies]
once_cell.workspace = true
serde.workspace = true

[dev-dependencies]
anyhow.workspace = true
insta.workspace = true
